// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jtlmfjbskmupwjrbcwvg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp0bG1mamJza211cHdqcmJjd3ZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4NjQ5NTQsImV4cCI6MjA1OTQ0MDk1NH0.D4NGAKYoifqn5g72ZrSb3k8IQLKsp7BTKIHm3bnoxns";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);